CREATE DATABASE CrudDataBase;
USE CrudDataBase;
CREATE TABLE crudNodeAngel(
    id INT(6) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phone VARCHAR(100) NOT NULL,
    address VARCHAR(300) NOT NULL   
)AUTO_INCREMENT=1